version: 1
disable_existing_loggers: False

formatters:
    standard:
        format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
    json:
        (): utils.logger.JsonFormatter
        format: "%(asctime)s %(levelname)s %(name)s %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    test_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: json
        filename: logs/test_execution/test.log
        maxBytes: 10485760  # 10MB
        backupCount: 5
        encoding: utf8

    db_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: json
        filename: logs/database/db.log
        maxBytes: 10485760
        backupCount: 5
        encoding: utf8

    report_file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: logs/reports/report_gen.log
        maxBytes: 10485760
        backupCount: 5
        encoding: utf8

    pipeline_file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: logs/pipeline/pipeline.log
        maxBytes: 10485760
        backupCount: 5
        encoding: utf8

loggers:
    test_execution:
        level: DEBUG
        handlers: [console, test_file]
        propagate: False

    database:
        level: DEBUG
        handlers: [db_file]
        propagate: False

    reporting:
        level: INFO
        handlers: [report_file]
        propagate: False

    pipeline:
        level: INFO
        handlers: [pipeline_file]
        propagate: False

root:
    level: INFO
    handlers: [console]
