name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ecommerce_automation/requirements.txt
        pip install allure-pytest
    - name: Run tests with Allure
      run: |
        pytest ecommerce_automation/tests --alluredir=allure-results
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.8
      with:
        allure_results: allure-results
        allure_report: allure-report
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
